Numpy

install numpy

In [1]:
import numpy as np

Creating an array.
decide how many dimensions 

In [2]:
OneDim = np.array([1,2,3])
#this looks similar to a list with an array method attached to it.
OneDim.shape

(3,)

In [3]:
#shape above is 3 because it is 3 numbers, just straight.
OneDim

array([1, 2, 3])

In [4]:
OneDim.dtype

dtype('int32')

In [5]:
#changing data type
OneDim.astype('float32')

array([1., 2., 3.], dtype=float32)

In [6]:
oneDimen = np.array([1,2,3], dtype = "float32")
oneDimen.dtype

dtype('float32')

In [31]:
#for 2 dimentional
twoDim = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = "float32")
print(twoDim.shape)
print(twoDim)
tran = twoDim.T
print(tran)

(3, 3)
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [8]:
#mutidimension
multidim = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])
print(multidim.shape)
multidim

(1, 4, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

the above is a 4 x 3 matrix. row x column is how to name matrices

In [9]:
zero = np.zeros(4)
zero

array([0., 0., 0., 0.])

In [10]:
five = np.ones(4)
five

array([1., 1., 1., 1.])

In [11]:
#the above returns floats, to make it int do the following
five = np.ones(4, dtype = np.int64)
five

array([1, 1, 1, 1], dtype=int64)

***RANGE***

In [12]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.arange(9.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [14]:
np.arange(10, 100, 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [16]:
np.random.rand(4,3)

array([[0.22072324, 0.54786044, 0.6520062 ],
       [0.34873862, 0.98520728, 0.23484523],
       [0.12256177, 0.97788523, 0.81509541],
       [0.38402154, 0.12323116, 0.29375649]])

*MATHS OPERATIONS*

In [17]:
array1 = OneDim

In [18]:
array2 = np.array([4, 5, 6])

In [19]:
array1 + array2

array([5, 7, 9])

In [20]:
array2/array1

array([4. , 2.5, 2. ])

In [21]:
np.add(array1, array2)

array([5, 7, 9])

In [22]:
np.divide(array2, array1)

array([4. , 2.5, 2. ])

In [23]:
np.sqrt(twoDim)

array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898],
       [2.6457512, 2.828427 , 3.       ]], dtype=float32)

In [24]:
np.multiply(array1, array2)

array([ 4, 10, 18])

In [25]:
array1.dot(array2) #this multiplies like the above but adds it to one integer called scalar

32

In [26]:
print(multidim.shape)
transposed = multidim.T #changes 2x3 to 3x2 matrix
print(transposed.shape)

(1, 4, 3)
(3, 4, 1)


In [27]:
#multiply usually arrays of the same shape, or at least have one column in common. U can transpose to make this happen

In [28]:
np.random.uniform(10, 50, 5)

array([23.84355228, 12.20027347, 40.19279126, 43.36706122, 20.66440359])

In [29]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [30]:
print(multidim)
print(transposed)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[[[ 1]
  [ 4]
  [ 7]
  [10]]

 [[ 2]
  [ 5]
  [ 8]
  [11]]

 [[ 3]
  [ 6]
  [ 9]
  [12]]]
